#pragma once

#define CTSS_VM_FEATURE_FLOAT
//#define CTSS_VM_FEATURE_BOUNDS
#define CTSS_VM_FEATURE_PRINT
//#define CTSS_VM_FEATURE_TRACE
#define CTSS_VM_FEATURE_TRACE_INLINING
#define CTSS_VM_FEATURE_INLINE
#define CTSS_VM_FEATURE_IO

#define CTSS_VM_CUSTOM_TYPES void *synthOp;

#define CTSS_VM_INLINE_THRESHOLD 4
